# Base image for container
FROM node:alpine3.20 as build

# Environment variables used
# ENV DATABASE_SERVER= DATABASE_USER= DATABASE_USER_PASSWORD= DATABASE= PORT=
ENV PORT=9000

# Create app directory
WORKDIR /build

# Copy dependency definitions
COPY package*.json ./

# Install dependencies
RUN npm install

COPY . .

RUN npm run build

FROM node:alpine3.20 as production

WORKDIR /buld

COPY package*.json ./

# Omit dev dependencies
RUN npm ci --only=production --omit=dev

COPY --from=build /build/dist ./dist

# Expose port
EXPOSE 9000

# Run the app
ENTRYPOINT [ "npm", "run", "start" ]