# Base image for container
FROM node:alpine3.20 as base

# Environment variables used
# ENV DATABASE_SERVER= DATABASE_USER= DATABASE_USER_PASSWORD= DATABASE= PORT=
ENV PORT=3000

# Create app directory
WORKDIR /app

# Copy dependency definitions
COPY package*.json ./

# Install dependencies
RUN npm install

COPY . .
FROM base as builder
WORKDIR /app
RUN npm run build

# Expose port
EXPOSE 3000

# Run the app
ENTRYPOINT [ "node", "/app/dist/server.js" ]